//user reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_LOCATION_PROVINCE_LOGREG = 'SET_LOCATION_PROVINCE_LOGREG';
export const SET_ADD_ID_KOTA_LOGREG = 'SET_ADD_ID_KOTA_LOGREG';
export const SET_ADD_KOTA_LOGREG = 'SET_ADD_KOTA_LOGREG';
export const SET_ADD_KECAMATAN_LOGREG = 'SET_ADD_KECAMATAN_LOGREG';
export const SET_POTONGAN_MEMBERSHIP = 'SET_POTONGAN_MEMBERSHIP';

//data product reducer types
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_SINGLE_PRODUCT = 'GET_ALL_SINGLE_PRODUCT'; // ini cuma dapet 4 doang productnya
export const GET_TRUE_ALL_SINGLE_PRODUCT = 'GET_TRUE_ALL_SINGLE_PRODUCT';
export const GET_ALL_SINGLE_PRODUCT_BY_PAGE = 'GET_ALL_SINGLE_PRODUCT_BY_PAGE'; // ini dapet 6 productnya

export const GET_TRUE_ALL_BUNDLING_PRODUCT = 'GET_TRUE_ALL_BUNDLING_PRODUCT';
export const GET_ALL_BUNDLING_PRODUCT = 'GET_ALL_BUNDLING_PRODUCT';
export const GET_ALL_BUNDLING_PRODUCT_BY_PAGE = 'GET_ALL_BUNDLING_PRODUCT_BY_PAGE';

export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const SET_CHANGEABLE_PRODUCT_NAME = 'SET_CHANGEABLE_PRODUCT_NAME';
export const LOADING_PRODUCT = 'LOADING_PRODUCT';

//ID Uniq Reducer
export const SET_ID_UNIQ_CART_USER = 'SET_ID_UNIQ_CART_USER';

//ID ORDER ID
export const SET_ORDER_ID = 'SET_ORDER_ID';

// data bagReducer
export const SET_ADD_TO_BAG = 'SET_ADD_TO_BAG';
export const LOADING_ON_BAG = 'LOADING_ON_BAG';
export const DELETE_BAG = 'DELETE_BAG';
export const DELETE_ALL_BAG = 'DELETE_ALL_BAG';
export const TOTAL_PRICE = 'TOTAL_PRICE';
export const SET_SHIPPING_FEE = 'SET_SHIPPING_FEE';
export const SET_TOTAL_PLUS_SHIPPING = 'SET_TOTAL_PLUS_SHIPPING';
export const SET_ADD_KURIR = 'SET_ADD_KURIR';

//shipping address reducer types
export const RESET_LOCATION = 'RESET_LOCATION';
export const SET_LOCATION_PROVINCE = 'SET_LOCATION_PROVINCE';
export const SET_ADD_ID_KOTA = 'SET_ADD_ID_KOTA';
export const SET_ADD_KOTA = 'SET_ADD_KOTA';
export const SET_ADD_ID_KECAMATAN = 'SET_ADD_ID_KECAMATAN';
export const SET_ADD_KECAMATAN = 'SET_ADD_KECAMATAN';
export const SET_ID_PROV = 'SET_ID_PROV';

//Data Kurir
export const GET_DETAIL_DATA_KURIR = 'GET_DETAIL_DATA_KURIR';
export const SET_KURIR_NAME = 'SET_KURIR_NAME';
export const GET_DETAIL_DATA_KURIR_FOR_CHECKOUT = 'GET_DETAIL_DATA_KURIR';
export const SET_KURIR_NAME_FOR_CHECKOUT = 'SET_KURIR_NAME_FOR_CHECKOUT';

//ui reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_ERRORS_FORGOT_PASSWORD_SUBMIT = 'SET_ERRORS_FORGOT_PASSWORD_SUBMIT';
export const CLEAR_ERRORS_FORGOT_PASSWORD_SUBMIT = 'CLEAR_ERRORS_FORGOT_PASSWORD_SUBMIT';
export const SET_ERRORS_REGISTER = 'SET_ERRORS_REGISTER';
export const CLEAR_ERRORS_REGISTER = 'CLEAR_ERRORS_REGISTER';
export const SET_ERRORS_CHECKOUT_BUTTON = 'SET_ERRORS_CHECKOUT_BUTTON';
export const CLEAR_ERRORS_CHECKOUT_BUTTON = 'CLEAR_ERRORS_CHECKOUT_BUTTON';
export const SET_ERRORS_EMPTY_BAG = 'SET_ERRORS_EMPTY_BAG';
export const CLEAR_ERRORS_EMPTY_BAG = 'CLEAR_ERRORS_EMPTY_BAG';
export const LOADING_UI = 'LOADING_UI';
export const LOADING_BUTTON_PAYNOW = 'LOADING_BUTTON_PAYNOW';
export const LOADING_BUTTON_PAYLATTER = 'LOADING_BUTTON_PAYLATTER';

export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const STOP_LOADING_BUTTON_PAYNOW = 'STOP_LOADING_BUTTON_PAYNOW';
export const STOP_LOADING_BUTTON_PAYLATTER = 'STOP_LOADING_BUTTON_PAYLATTER';

//URL_HeadnavReducers types
export const SET_HOME = 'SET_HOME';
export const SET_ABOUT_US = 'SET_ABOUT_US';
export const SET_PRODUCT_PAGE = 'SET_PRODUCT_PAGE';
export const SET_HOW_TO_BUY = 'SET_HOW_TO_BUY';
export const SET_CONTACT_US = 'SET_CONTACT_US';
export const SET_MAIN_URL = 'SET_MAIN_URL';
export const SET_DETAIL_PRODUCT_URL = 'SET_DETAIL_PRODUCT_URL';
export const SET_CHANGEABLE_URL = 'SET_CHANGEABLE_URL';

//FORM login
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';

// DATA USER
export const SET_GET_ALL_DATA_USER = 'SET_GET_ALL_DATA_USER';

// GET DETAIL ORDER USERS
export const SET_GET_DATA_USER_ORDER = 'SET_GET_DATA_USER_ORDER';

// GET DETAIL ORDER USERS in EACH USER DASHBOARD
export const SET_GET_DATA_USER_ORDER_IN_USER_DASHBOARD = 'SET_GET_DATA_USER_ORDER_IN_USER_DASHBOARD';

// THE COMMENT
export const GET_COMMENT = 'GET_COMMENT';

// ALL NOTIFICATION
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';

// GET ORDER BY ORDER ID FOR RINCIAN PESANAN ADMIN
export const GET_ORDER_BY_ID_ORDER = 'GET_ORDER_BY_ID_ORDER';
export const SET_GET_DATA_USER_HISTORY_ORDER = 'SET_GET_DATA_USER_HISTORY_ORDER';

// SITUSKU
export const SET_GET_DATA_SETTING_ABOUT_US = 'SET_GET_DATA_SETTING_ABOUT_US';
export const SET_GET_DATA_MAIN_BANNER = 'SET_GET_DATA_MAIN_BANNER';
